### ISSUE TITLE
在魅族16s，Android9上定位接口不返回

### ISSUE THREAD

**Issue by davidche1116** [zenganiu/flutter_z_location#2]
在魅族16s手机（Android9）使用await FlutterZLocation.getCoordinate();一直不返回往下执行了。状态栏一直有系统获取定位的GPS图标闪烁

**Comment by davidche1116** [comment]
我找到问题原因了，是手机GPS信号不太好，在室内精确定位就是无法返回。建议把定位精确度参数能通过接口传入。
我将GpsListener.java中第30行的criteria.setAccuracy(Criteria.ACCURACY_FINE);改为criteria.setAccuracy(Criteria.ACCURACY_COARSE);就可以了

**Comment by zenganiu** [comment]
已处理
