### ISSUE TITLE
手机没有开启定位时，会出现崩溃问题。

### ISSUE THREAD

**Issue by weilei131** [zenganiu/flutter_z_location#3]
查询到类在：GpsListener -> onProviderDisabled，出现异常
修改如下：
@Override
    public void onProviderDisabled(@NonNull String provider) {
        //LocationListener.super.onProviderDisabled(provider);
        result.error("-1","未开启定位,请在导航中开启定位(位置信息)。"+provider,"");
    }

不需要调用父类对象，直接发送错误出来。

**Comment by zenganiu** [comment]
已处理，非常感谢反馈的问题
